BLE_ADDR_SENSOR_NECK = "54:6C:0E:B6:DC:03"
BLE_ADDR_SENSOR_SHOULDER_L = "54:6C:0E:53:3A:A1"
BLE_ADDR_SENSOR_SHOULDER_R = "54:6C:0E:53:34:DF"
BLE_ADDR_SENSOR_BACK = "54:6C:0E:52:EE:26"

BLE_ADDR_LIST = (
    BLE_ADDR_SENSOR_SHOULDER_L,
    BLE_ADDR_SENSOR_SHOULDER_R,
    BLE_ADDR_SENSOR_BACK,
    BLE_ADDR_SENSOR_NECK
)