STACK_BAR_PLOT_TITLE = "Stack Bar Plot of Postures"
PIE_PLOT_TITLE = "Pie Plot of Postures"

STACK_BAR_PLOT_DATE_PATH = "STACK_BAR_PLOT_DATE.png"
STACK_BAR_PLOT_DATE_BAD_PATH = "STACK_BAR_PLOT_DATE_BAD.png"

STACK_BAR_PLOT_HOUR_PATH = "STACK_BAR_PLOT_HOUR.png"
STACK_BAR_PLOT_HOUR_ALL_PATH = "STACK_BAR_PLOT_HOUR_ALL_PATH.png"

STACK_BAR_PLOT_HOUR_BAD_PATH = "STACK_BAR_PLOT_HOUR_BAD.png"
STACK_BAR_PLOT_HOUR_BAD_ALL_PATH = "STACK_BAR_PLOT_HOUR_BAD_ALL.png"

PIE_PATH = "PIE.png"
PIE_ALL_PATH = "PIE_ALL.png"