# BLE_ADDR_SENSOR_NECK = "54:6C:0E:53:3A:A1"
# BLE_ADDR_SENSOR_SHOULDER_L = "54:6C:0E:52:EE:26"
# BLE_ADDR_SENSOR_SHOULDER_R = "54:6C:0E:B6:DC:03"
# BLE_ADDR_SENSOR_BACK = "54:6C:0E:53:34:DF"
import os

PROJ_DIR = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
IO_DIR = os.path.join(PROJ_DIR, "io")


BLE_ADDR_SENSOR_NECK = "54:6C:0E:53:3A:A1"
BLE_ADDR_SENSOR_BACK_MID = "54:6C:0E:52:EE:26"
BLE_ADDR_SENSOR_BACK_LOW = "54:6C:0E:B6:DC:03"
# BLE_ADDR_SENSOR_BACK = "54:6C:0E:53:34:DF"

# BLE_NAME_SENSOR_NECK = "neck"
# BLE_NAME_SENSOR_SHOULDER_L = "shoulder_l"
# BLE_NAME_SENSOR_SHOULDER_R = "shoulder_r"
# BLE_NAME_SENSOR_BACK = "back"

BLE_NAME_SENSOR_NECK = "neck"
BLE_NAME_SENSOR_BACK_MID = "back_mid"
BLE_NAME_SENSOR_BACK_LOW = "back_low"
# BLE_NAME_SENSOR_BACK = "back"

MQTT_TOPIC_CLASSIFY = "Group_B2/IMAGE/classify"
MQTT_TOPIC_PREDICT = "Group_B2/IMAGE/predict"

CLASSIFICATION_FORWARD = 0
CLASSIFICATION_LEFT = 2
CLASSIFICATION_RIGHT = 3
CLASSIFICATION_BACKWARD = 1
CLASSIFICATION_PROPER = 4
CLASSIFICATION_UNKNOWN = 5

MQTT_CLASSIFICATION_FORWARD = "Lean Forward"
MQTT_CLASSIFICATION_LEFT = "Lean Left"
MQTT_CLASSIFICATION_RIGHT = "Lean Right"
MQTT_CLASSIFICATION_BACKWARD = "Lean Backward"
MQTT_CLASSIFICATION_PROPER = "Good posture"
MQTT_CLASSIFICATION_UNKNOWN = "Unknown"

CLASSIFICATIONS = [
    CLASSIFICATION_FORWARD,
    CLASSIFICATION_LEFT,
    CLASSIFICATION_RIGHT,
    CLASSIFICATION_BACKWARD,
    CLASSIFICATION_PROPER,
    CLASSIFICATION_UNKNOWN
]

MQTT_CLASSIFICATIONS = [
    MQTT_CLASSIFICATION_FORWARD,
    MQTT_CLASSIFICATION_LEFT,
    MQTT_CLASSIFICATION_RIGHT,
    MQTT_CLASSIFICATION_BACKWARD,
    MQTT_CLASSIFICATION_PROPER,
    MQTT_CLASSIFICATION_UNKNOWN
]

# BLE_ADDR_LIST = [
#     BLE_ADDR_SENSOR_SHOULDER_L,
#     BLE_ADDR_SENSOR_SHOULDER_R,

#     BLE_ADDR_SENSOR_BACK,
#     BLE_ADDR_SENSOR_NECK
# ]

# BLE_ADDR_TO_NAME = {
#     BLE_ADDR_SENSOR_BACK: BLE_NAME_SENSOR_BACK,
#     BLE_ADDR_SENSOR_NECK: BLE_NAME_SENSOR_NECK,
#     BLE_ADDR_SENSOR_SHOULDER_L: BLE_NAME_SENSOR_SHOULDER_L, 
#     BLE_ADDR_SENSOR_SHOULDER_R: BLE_NAME_SENSOR_SHOULDER_R
# }

BLE_ADDR_LIST = [
    # BLE_ADDR_SENSOR_BACK_MID,
    # BLE_ADDR_SENSOR_BACK_LOW,
    BLE_ADDR_SENSOR_NECK
]


BLE_ADDR_TO_NAME = {
    # BLE_ADDR_SENSOR_BACK: BLE_NAME_SENSOR_BACK,
    BLE_ADDR_SENSOR_NECK: BLE_NAME_SENSOR_NECK,
    BLE_ADDR_SENSOR_BACK_MID: BLE_NAME_SENSOR_BACK_MID, 
    BLE_ADDR_SENSOR_BACK_LOW: BLE_NAME_SENSOR_BACK_LOW
}

BLE_NAME_LIST = [BLE_ADDR_TO_NAME[i] for i in BLE_ADDR_LIST]


MODE_EXPORT_DATA = 1
MODE_RT_SCAN = 0